### ISSUE TITLE
请问怎么配置？

### ISSUE THREAD

**Issue by B1anker** [4n70n/SGUEasyDrcomGUI#1]
我修改了两处ip地址，为什么拨号的时候ip还是192.168.199.177呢？

**Comment by 4n70n** [comment]
IP是在DrcomDealerU31.mm 和DrcomDealerU62.mm 里修改，把我学校的192.168.127.129改为你学校的认证服务器IP，另外在drcom_dealer_u31.hpp 和drcom_dealer_u62.hpp 里还要把0xDC,0x02改为你们学校的SALT，具体的SALT还需要你自己用WireShark抓包
