### ISSUE TITLE
你好，在sgu校内测试mac版21分钟掉线？！

### ISSUE THREAD

**Issue by laijingwu** [4n70n/SGUEasyDrcomGUI#2]
看了下readme里写的，问题应该是心跳包没有做好的原因吗？
最近我也分析了一下针对sgu西区的drcom 5.2.1x版的协议，在找这方面的资料。

**Comment by 4n70n** [comment]
对的，Win32版也有同样的问题，我现在就是在研究这个问题，wireshark抓包发现有几个关键认证包没有发出去，现在在断断续续的修改
